GRANT ALL PRIVILEGES ON DATABASE imprintdb to imprintuser;
ALTER DATABASE imprintdb OWNER TO imprintuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO imprintuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO imprintuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO imprintuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO imprintuser;
